RecruitPNG.Web/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RecruitPNG.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles="Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RecruitPNG.Web/Areas/Admin/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitPNG.Data;
using RecruitPNG.Models;
using RecruitPNG.Services;
using Microsoft.AspNetCore.Authorization;

namespace RecruitPNG.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles="Admin")]
    public class JobsController : Controller
	{
		private readonly IJobService jobService;
		private readonly ICompanyService companyService;
        private readonly ICountryService countryService;
        private readonly ICityService cityService;
        private readonly ICountyService countyService;

        public JobsController(IJobService jobService, ICompanyService companyService, ICountryService countryService, ICityService cityService, ICountyService countyService)
		{
			this.jobService = jobService;
			this.companyService = companyService;
            this.countryService = countryService;
            this.cityService = cityService;
            this.countyService = countyService;
		}


		// GET: Admin/Jobs
		public IActionResult Index()
		{
			var jobs = jobService.GetAll();
			return View(jobs);
		}

		// GET: Admin/Jobs/Details/5
		public IActionResult Details(string id)
		{
			var job = jobService.Get(id);
			return View(job);

		}

		// GET: Admin/Jobs/Create
		public IActionResult Create()
		{
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name");
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            var job = new Job
            {
                PublishDate = DateTime.Now,
                EndDate = DateTime.Now.AddMonths(1)
            };
            return View(job);
		}

		// POST: Admin/Jobs/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("Title,Description,CompanyId,CountryId,CityId,CountyId,PublishDate,EndDate,IsApproved,IsActive,IsFeatured,Position,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] Job job)
		{
			if (ModelState.IsValid)
			{
				jobService.Insert(job);
				return RedirectToAction(nameof(Index));
			}
			
			// GET: Admin/Jobs/Edit/5
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name");
			return View(job);
		}
        public IActionResult Edit(string id)
        {
            var job = jobService.Get(id);
            ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            //ViewBag.CityId = new SelectList(cityService.GetAll(), "Id", "Name", job.CityId);
            //ViewBag.CountyId = new SelectList(countyService.GetAll(), "Id", "Name", job.CountyId);
            return View(job);
            
        }
        // POST: Admin/Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(string id, [Bind("Title,Description,CompanyId,CountryId,CityId,CountyId,PublishDate,EndDate,IsApproved,IsActive,IsFeatured,Position,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] Job job)
		{
			if (id != job.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					jobService.Update(job);
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!JobExists(job.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name"); 
			return View(job);
		}

		// GET: Admin/Jobs/Delete/5
		public IActionResult Delete(string id)
		{
			var job = jobService.Get(id);
			return View(job);
		}

		// POST: Admin/Jobs/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(string id)
		{
			jobService.Delete(id);
			return RedirectToAction(nameof(Index));
		}

		private bool JobExists(string id)
		{
			return jobService.GetAll().Any(e => e.Id == id);
		}
	}
}

RecruitPNG.Web/Controllers/JobController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RecruitPNG.Models;
using RecruitPNG.Services;
using RecruitPNG.Web.ViewModels;

namespace RecruitPNG.Web.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobService jobService;
        private readonly ICompanyService companyService;
        private readonly IResumeService resumeService;
        private readonly IJobApplicationService jobApplicationService;
        //addaed
        private readonly ICountryService countryService;
        private readonly ICityService cityService;
        private readonly ICountyService countyService;

        public JobController(IJobService jobService, ICompanyService companyService, IResumeService resumeService,
            IJobApplicationService jobApplicationService, ICityService cityService, ICountyService countyService, ICountryService countryService)
        {
            this.jobService = jobService;
            this.companyService = companyService;
            this.resumeService = resumeService;
            this.jobApplicationService = jobApplicationService;
            this.countryService = countryService;
            this.cityService = cityService;
            this.countyService = countyService;
        }
        public IActionResult Index()
        {
            var jobs = jobService.GetAll();
            return View(jobs);
        }

        [Authorize(Roles = "Company")]
        //Create
        public IActionResult Create()
        {

            var job = new Job();
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name");
            //add
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            job.PublishDate = DateTime.Now;
            job.EndDate = job.PublishDate.AddDays(30);
            return View(job);

        }
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Job job)
        {
            if (ModelState.IsValid)
            {
                jobService.Insert(job);
                return RedirectToAction(nameof(Edit), new { id = job.Id, saved = true });
            }
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            return View(job);

        }
        [Authorize(Roles = "Company")]
        //Edit
        public IActionResult Edit(string id, bool saved)
        {
            var job = jobService.Get(id);
            ViewBag.Saved = saved;
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            return View(job);
        }
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, Job job)
        {
            if (ModelState.IsValid)
            {
                jobService.Update(job);
                return RedirectToAction(nameof(Edit), new { id = job.Id, saved = true });
            }
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            return View(job);

        }
        [Authorize(Roles = "Company")]
        //Delete
        public IActionResult Delete(string id)
        {
            jobService.Delete(id);
            return RedirectToAction("MyJobs");
        }
        [Authorize(Roles = "Company")]
        //MyJobs
        public IActionResult MyJobs()
        {
            var myJobs = jobService.GetAllByUserName(User.Identity.Name).ToList();
            return View(myJobs);
        }

        //Details
        public IActionResult Details(string id)
        {
            var job = jobService.Get(id);
            return View(job);

        }
        [Authorize(Roles = "Candidate")]
        public IActionResult Apply(string jobId)
        {
            var jobEmployer = "";

            var job = jobService.Get(jobId);
            jobEmployer = job.Company.Name; // kime / firma adı

            //var message = new Message() { To = job.CompanyId, ToName = jobEmployer, Title = job.Title };

            var ja = new JobApplication() { JobId = jobId};
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName");
            ViewData["JobId"] = new SelectList(jobApplicationService.GetAll(), "Id", "Name");
            return View(ja);
        }
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        public IActionResult Apply(JobApplication ja)
        {
            if (ModelState.IsValid)
            {
                jobApplicationService.Insert(ja);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", ja.ResumeId);
            return View(ja);

        }

        public IActionResult Success()
        {
            return View();
        }

    }
}

RecruitPNG.Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RecruitPNG.Models;
using RecruitPNG.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecruitPNG.Web.Controllers
{
    public class MessagesController : ControllerBase
    {
        private readonly IMessageService messageService;
        private readonly ICompanyService companyService;
        private readonly IResumeService resumeService;
        private readonly IJobService jobService;
        public MessagesController(IMessageService messageService, ICompanyService companyService, IResumeService resumeService, IJobService jobService)
        {
            this.messageService = messageService;
            this.companyService = companyService;
            this.resumeService = resumeService;
            this.jobService = jobService;
        }
        [Authorize(Roles = "Company")]
        public IActionResult MyMessagesSentToMyCompanies()
        {
            var mycompanies = companyService.GetAllByUserName(User.Identity.Name).Select(c=>c.Id).ToList();
            var mymessages = messageService.GetAllByTo(mycompanies);
            return View(mymessages);
        }
        [Authorize(Roles = "Candidate")]
        public IActionResult MyMessagesSentToMyResumes()
        {
            var myresumes = resumeService.GetAllByUserName(User.Identity.Name).Select(c => c.Id).ToList(); // resumes
            var mymessages = messageService.GetAllByTo(myresumes);
            return View(mymessages);
        }
        [Authorize(Roles = "Company")]
        public IActionResult SendMessageToResume(string resumeId)
        {
            var toName = "";
            
            var resume = resumeService.Get(resumeId);
            toName = resume.ResumeName; // resuem name
           
            var message = new Message(){ To = resumeId, ToName = toName };
            ViewBag.MyCompanies = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name"); // resume
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Company")]
        public IActionResult SendMessageToResume(Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = companyService.Get(message.From).Name; // kimden
                message.ToName = resumeService.Get(message.To).ResumeName; // kime
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyCompanies = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", message.From);
            return View(message);
        }

        public IActionResult Success()
        {
            return View();
        }

        public IActionResult Details(string id)
        {
            var message = messageService.Get(id);

            return View(message);

        }
        // Candidate to employer
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToCompany(string companyId) // companyId: message to employer job
        {
            
            var toName = "";

            var company = companyService.Get(companyId);
            toName = company.Name + " " + company.ContactName; // employer contat

            var message = new Message() { To = companyId, ToName = toName };
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName"); // select to 
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToCompany(Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = resumeService.Get(message.From).ResumeName; // kimden / özgeçmiş
                message.ToName = companyService.Get(message.To).Name; // kime / firma
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", message.From);
            return View(message);
        }

        // aday ilan sahibi firmaya mesaj gönderiyor
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToJob(string jobId)
        {
            var toName = "";

            var job = jobService.Get(jobId);
            toName = job.Company.Name; // kime / firma adı

            var message = new Message() { To = job.CompanyId, ToName = toName, Title = job.Title };
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName"); // kimden
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToJob(string jobId, Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = resumeService.Get(message.From).ResumeName; // kimden
                message.ToName = companyService.Get(message.To).Name; // kime
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", message.From);
            return View(message);
        }
    }
}

RecruitPNG.Web/Views/Home/Index - Copy.cshtml
@{
    ViewData["Title"] = "RecruitPNG";
}

<link href="~/assets/pages/css/search.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/pages/css/about.css" rel="stylesheet" type="text/css" />
<link href="~/css/custom.css" rel="stylesheet" type="text/css" />


<!-- BEGIN PAGE TITLE -->
@section Slider {
<div class="row margin-bottom-40 about-header">
    <div class="col-md-12">
        <h1>Online recruitment portal</h1>
        <h2>We do much more than just bringing job seekers and employers togather</h2>
        <a asp-action="Create" asp-controller="Resumes" class="btn btn-secondary">Start by creating your resume</a>
    </div>
</div>
}


@*<div>

        @if (((IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs).Count() > 0)
        {
            @foreach (var item in (IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs)
            {
                <div class="card">
                    <div class="card-title">
                        @item.Title
                    </div>
                    <p class="card-body">
                        @item.Description
                    </p>
                </div>
            }
        }
    </div>*@
<table class="table table-hover">
    <tbody>
        <h3>Featured Jobs</h3>
        @if (((IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs).Count() > 0)
        {
            @foreach (var item in (IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs)
            {


                <tr>
                    <td>
                        <a href="javascript:;">
                            <img src="~/Uploads/Companies/@item.Company?.Logo" alt="@item.Company?.Name" width="80" />
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Companies" asp-action="Details" asp-route-id="@item.CompanyId">@item.Company?.Name</a>
                    </td>
                    <td>
                        <strong>
                            <a asp-action="Details" asp-controller="Jobs" asp-route-id="@item.Id">@item.Title</a>
                        </strong>
                    </td>
                    <td> @item.Company?.County?.Name </td>
                    <td>
                        <a asp-action="Apply" asp-controller="Jobs" asp-route-jobid="@item.Id" class="btn btn-sm btn-primary">
                            Apply
                        </a>
                        <a asp-action="SendMessageToJob" asp-controller="Messages" asp-route-jobId="@item.Id" class="btn btn-sm btn-success">
                            Send message
                        </a>
                    </td>
                </tr>
            }
        }
        else if (!string.IsNullOrEmpty(ViewBag.search))
        {
            <tr>
                <td colspan="5">Your search results...</td>
            </tr>

        }
        else
        {

            <tr>
                <td colspan="5">No jobs posted yet...</td>
            </tr>
        }
    </tbody>
</table>

RecruitPNG.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "RecruitPNG";
}
<link href="/assets/pages/css/search.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/pages/css/about.css" rel="stylesheet" type="text/css" />
<link href="~/css/custom.css" rel="stylesheet" type="text/css" />
@section Slider {
    <!-- BEGIN PAGE TITLE -->
    <div class="row margin-bottom-40 about-header">
        <div class="col-md-12">
            <h1>Complete recruitment portal</h1>
            <h2>We do much more than just bringing job seekers and employers togather</h2>
            <a asp-action="Create" asp-controller="Resumes" class="btn btn-outline-info">Create your resume</a>
        </div>
    </div>
}
<!-- END PAGE BREADCRUMBS -->
<div class="search-page search-content-4">
    <div class="search-bar bordered">
        <form method="get">
            <div class="row">
                <div class="col-sm-2" style="padding-top:15px">
                    <label for="search" class="control-label uppercase bold pull-right">Search by title</label>
                </div>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter job title to search..." id="search" name="search" value="@ViewBag.Search">
                        <span class="input-group-btn">
                            <button class="btn green-soft uppercase bold btn-info" type="submit">Search</button>
                        </span>
                    </div>

                </div>
                <div class="col-sm-2 extra-buttons">
                    <button class="btn grey-steel uppercase bold" type="submit" onclick="$('#search').val('')">Reset</button>
                </div>
            </div>
        </form>
    </div>
    <div class="search-table table-responsive">
        <h3 style="text-align:center">
            @if (string.IsNullOrEmpty(ViewBag.search))
            {<text>Featured Jobs</text>}
        else
        {<text>Search Results</text>}
    </h3>
    <table class="table table-bordered table-striped table-condensed">
        <thead class="bg-blue">
            <tr>
                <th>
                    <a href="javascript:;">Logo</a>
                </th>
                <th>
                    <a href="javascript:;">Employer</a>
                </th>
                <th>
                    <a href="javascript:;">Position</a>
                </th>
                <th>
                    <a href="javascript:;">Location</a>
                </th>
                <th><a href="javascript:;">Action</a></th>
            </tr>
        </thead>
        <tbody>
            @if (((IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs).Count() > 0)
            {
                @foreach (var item in (IEnumerable<RecruitPNG.Models.Job>)ViewBag.FeaturedJobs)
                {
                    <tr>
                        <td>
                            <a href="javascript:;">
                                <img src="~/Uploads/Companies/@item.Company?.Logo" alt="@item.Company?.Name" width="80" />
                            </a>
                        </td>
                        <td>
                            <a asp-controller="Companies" asp-action="Details" asp-route-id="@item.CompanyId">@item.Company?.Name</a>
                        </td>
                        <td>
                            <strong>
                                <a asp-action="Details" asp-controller="Job" asp-route-id="@item.Id">@item.Title</a>
                            </strong>
                        </td>
                        <td> @item.Company?.County?.Name </td>
                        <td>
                            <a asp-action="Apply" asp-controller="Job" asp-route-jobid="@item.Id" class="btn btn-sm btn-primary">
                                Apply
                            </a>
                            <a asp-action="SendMessageToJob" asp-controller="Messages" asp-route-jobId="@item.Id" class="btn btn-sm btn-success">
                                Send message
                            </a>
                        </td>
                    </tr>
                }
            }
            else if (!string.IsNullOrEmpty(ViewBag.search))
            {
                <tr>
                    <td colspan="5">Your search results...</td>
                </tr>

            }
            else
            {

                <tr>
                    <td colspan="5">No job found...</td>
                </tr>
            }
        </tbody>
    </table>
</div>
</div>