RecruitPNG.Web/Areas/Admin/Controllers/JobApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitPNG.Data;
using RecruitPNG.Models;
using RecruitPNG.Services;
using Microsoft.AspNetCore.Authorization;

namespace RecruitPNG.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles="Admin")]
    public class JobApplicationsController : Controller
    {
        private readonly IJobApplicationService jobApplicationService;
        private readonly IJobService jobService;
        private readonly IResumeService resumeService;

        public JobApplicationsController(IJobApplicationService jobApplicationService, IJobService jobService, IResumeService resumeService)
        {
            this.jobApplicationService = jobApplicationService;
            this.jobService = jobService;
            this.resumeService = resumeService;
        }

        // GET: Admin/JobApplications
        public IActionResult Index()
        {
            return View(jobApplicationService.GetAll());
        }

        // GET: Admin/JobApplications/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = jobApplicationService.Get(id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // GET: Admin/JobApplications/Create
        public IActionResult Create()
        {
            
            ViewData["JobId"] = new SelectList(jobService.GetAll(), "Id", "Title");
            ViewData["ResumeId"] = new SelectList(resumeService.GetAll(), "Id", "ResumeName");
            var jobApplication = new JobApplication();
            return View(jobApplication);
        }

        // POST: Admin/JobApplications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ResumeId,JobId,Title,Description,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (ModelState.IsValid)
            {
                jobApplicationService.Insert(jobApplication);
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(jobService.GetAll(), "Id", "Title", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(resumeService.GetAll(), "Id", "ResumeName", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: Admin/JobApplications/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = jobApplicationService.Get(id);
            if (jobApplication == null)
            {
                return NotFound();
            }
            ViewData["JobId"] = new SelectList(jobService.GetAll(), "Id", "Title", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(resumeService.GetAll(), "Id", "ResumeName", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // POST: Admin/JobApplications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("ResumeId,JobId,Title,Description,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (id != jobApplication.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    jobApplicationService.Update(jobApplication);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(jobService.GetAll(), "Id", "Title", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(resumeService.GetAll(), "Id", "ResumeName", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: Admin/JobApplications/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = jobApplicationService.Get(id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // POST: Admin/JobApplications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            
            jobApplicationService.Delete(id);
            
            return RedirectToAction(nameof(Index));
        }

        private bool JobApplicationExists(string id)
        {
            return jobApplicationService.GetAll().Any(e => e.Id == id);
        }
    }
}

RecruitPNG.Web/Areas/Admin/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitPNG.Data;
using RecruitPNG.Models;
using RecruitPNG.Services;
using Microsoft.AspNetCore.Authorization;

namespace RecruitPNG.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles="Admin")]
    public class JobsController : Controller
	{
		private readonly IJobService jobService;
		private readonly ICompanyService companyService;
        private readonly ICountryService countryService;
        private readonly ICityService cityService;
        private readonly ICountyService countyService;

        public JobsController(IJobService jobService, ICompanyService companyService, ICountryService countryService, ICityService cityService, ICountyService countyService)
		{
			this.jobService = jobService;
			this.companyService = companyService;
            this.countryService = countryService;
            this.cityService = cityService;
            this.countyService = countyService;
		}


		// GET: Admin/Jobs
		public IActionResult Index()
		{
			var jobs = jobService.GetAll();
			return View(jobs);
		}

		// GET: Admin/Jobs/Details/5
		public IActionResult Details(string id)
		{
			var job = jobService.Get(id);
			return View(job);

		}

		// GET: Admin/Jobs/Create
		public IActionResult Create()
		{
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name");
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            var job = new Job
            {
                PublishDate = DateTime.Now,
                EndDate = DateTime.Now.AddMonths(1)
            };
            return View(job);
		}

		// POST: Admin/Jobs/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("Title,Description,CompanyId,CountryId,CityId,CountyId,PublishDate,EndDate,IsApproved,IsActive,IsFeatured,Position,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] Job job)
		{
			if (ModelState.IsValid)
			{
				jobService.Insert(job);
				return RedirectToAction(nameof(Index));
			}
			
			// GET: Admin/Jobs/Edit/5
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name");
			return View(job);
		}
        public IActionResult Edit(string id)
        {
            var job = jobService.Get(id);
            ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            //ViewBag.CityId = new SelectList(cityService.GetAll(), "Id", "Name", job.CityId);
            //ViewBag.CountyId = new SelectList(countyService.GetAll(), "Id", "Name", job.CountyId);
            return View(job);
            
        }
        // POST: Admin/Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(string id, [Bind("Title,Description,CompanyId,CountryId,CityId,CountyId,PublishDate,EndDate,IsApproved,IsActive,IsFeatured,Position,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] Job job)
		{
			if (id != job.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					jobService.Update(job);
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!JobExists(job.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewBag.CompanyId = new SelectList(companyService.GetAll(), "Id", "Name"); 
			return View(job);
		}

		// GET: Admin/Jobs/Delete/5
		public IActionResult Delete(string id)
		{
			var job = jobService.Get(id);
			return View(job);
		}

		// POST: Admin/Jobs/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(string id)
		{
			jobService.Delete(id);
			return RedirectToAction(nameof(Index));
		}

		private bool JobExists(string id)
		{
			return jobService.GetAll().Any(e => e.Id == id);
		}
	}
}

RecruitPNG.Web/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitPNG.Data;
using RecruitPNG.Models;

namespace RecruitPNG.Web.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Applications
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.JobApplications.Include(j => j.Job).Include(j => j.Resume);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Applications/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications
                .Include(j => j.Job)
                .Include(j => j.Resume)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // GET: Applications/Create
        public IActionResult Create()
        {
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id");
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResumeId,JobId,Title,Description,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jobApplication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: Applications/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications.FindAsync(id);
            if (jobApplication == null)
            {
                return NotFound();
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ResumeId,JobId,Title,Description,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (id != jobApplication.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jobApplication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: Applications/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications
                .Include(j => j.Job)
                .Include(j => j.Resume)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var jobApplication = await _context.JobApplications.FindAsync(id);
            _context.JobApplications.Remove(jobApplication);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobApplicationExists(string id)
        {
            return _context.JobApplications.Any(e => e.Id == id);
        }
    }
}

RecruitPNG.Web/Views/JobApplications/Create.cshtml
@model RecruitPNG.Models.JobApplication

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>JobApplication</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <select asp-for="JobId" class ="form-control" asp-items="ViewBag.JobId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ResumeId" class="control-label"></label>
                <select asp-for="ResumeId" class ="form-control" asp-items="ViewBag.ResumeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IPAddress" class="control-label"></label>
                <input asp-for="IPAddress" class="form-control" />
                <span asp-validation-for="IPAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecruitPNG.Web/Views/JobApplications/Delete.cshtml
@model RecruitPNG.Models.JobApplication

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobApplication</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Resume.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IPAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IPAddress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecruitPNG.Web/Views/JobApplications/Details.cshtml
@model RecruitPNG.Models.JobApplication

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>JobApplication</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resume)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Resume.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IPAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IPAddress)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RecruitPNG.Web/Views/JobApplications/Edit.cshtml
@model RecruitPNG.Models.JobApplication

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>JobApplication</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobId" class="control-label"></label>
                <select asp-for="JobId" class="form-control" asp-items="ViewBag.JobId"></select>
                <span asp-validation-for="JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResumeId" class="control-label"></label>
                <select asp-for="ResumeId" class="form-control" asp-items="ViewBag.ResumeId"></select>
                <span asp-validation-for="ResumeId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IPAddress" class="control-label"></label>
                <input asp-for="IPAddress" class="form-control" />
                <span asp-validation-for="IPAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecruitPNG.Web/Views/JobApplications/MyJobApplicants.cshtml
@model IEnumerable<RecruitPNG.Models.JobApplication>

@{
    ViewData["Title"] = "Applicants";
}

<link href="~/assets/cdn/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/cdn/responsive.dataTables.min.css" rel="stylesheet" />

<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Resume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th>
            <th class="text-nowrap all" data-orderable="false"> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Resumes" asp-route-id="@item.ResumeId">
                        @Html.DisplayFor(modelItem => item.Resume.ResumeName)
                    </a>
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Jobs" asp-route-id="@item.JobId">
                        @Html.DisplayFor(modelItem => item.Job.Title)
                    </a>
                </td>
                <td class="text-nowrap">
                    <a asp-action="Details" asp-route-id=@item.Id asp-controller="Applications" asp-area="" class="btn btn-info btn-sm">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script src="~/assets/cdn/jquery.dataTables.min.js"></script>
    <script src="~/assets/cdn/dataTables.responsive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblRecords').DataTable({
                responsive: true,
                "language":
                    { "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/English.json" }
            });
        });
    </script>
}

RecruitPNG.Web/Views/JobApplications/MyJobApplications.cshtml
@model IEnumerable<RecruitPNG.Models.JobApplication>

@{
    ViewData["Title"] = "Applications";
}

@*relplace with aspnet paging*@
<link href="~/assets/cdn/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/cdn/responsive.dataTables.min.css" rel="stylesheet" />

<table id="myTable" class="table">
    <thead>
        <tr>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Resume)
            </th>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Job)
            </th>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Title)
            </th>

            <th class="text-nowrap all" data-orderable="false"> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Resumes" asp-route-id="@item.ResumeId">
                        @Html.DisplayFor(modelItem => item.Resume.ResumeName)
                    </a>
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Jobs" asp-route-id="@item.JobId">
                        @Html.DisplayFor(modelItem => item.Job.Title)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>

                <td class="text-nowrap">
                    <a asp-action="Details" asp-route-id=@item.Id asp-controller="Applications" asp-area="" class="btn btn-info btn-sm">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script src="~/assets/cdn/jquery.dataTables.min.js"></script>
    <script src="~/assets/cdn/dataTables.responsive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblRecords').DataTable({
                responsive: true,
                "language":
                    { "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/English.json" }
            });
        });
    </script>
}