RecruitPNG.Web/Controllers/JobApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitPNG.Data;
using RecruitPNG.Models;

namespace RecruitPNG.Web.Controllers
{
    public class JobApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobApplicationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: JobApplications
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.JobApplications.Include(j => j.Job).Include(j => j.Resume);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: JobApplications/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications
                .Include(j => j.Job)
                .Include(j => j.Resume)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // GET: JobApplications/Create
        public IActionResult Create()
        {
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id");
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id");
            return View();
        }

        // POST: JobApplications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,JobId,ResumeId,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jobApplication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: JobApplications/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications.FindAsync(id);
            if (jobApplication == null)
            {
                return NotFound();
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // POST: JobApplications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Title,Description,JobId,ResumeId,Id,CreateDate,CreatedBy,UpdateDate,UpdatedBy,IPAddress")] JobApplication jobApplication)
        {
            if (id != jobApplication.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jobApplication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id", jobApplication.JobId);
            ViewData["ResumeId"] = new SelectList(_context.Resumes, "Id", "Id", jobApplication.ResumeId);
            return View(jobApplication);
        }

        // GET: JobApplications/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplications
                .Include(j => j.Job)
                .Include(j => j.Resume)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // POST: JobApplications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var jobApplication = await _context.JobApplications.FindAsync(id);
            _context.JobApplications.Remove(jobApplication);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobApplicationExists(string id)
        {
            return _context.JobApplications.Any(e => e.Id == id);
        }
    }
}

RecruitPNG.Web/Controllers/JobController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RecruitPNG.Models;
using RecruitPNG.Services;
using RecruitPNG.Web.ViewModels;

namespace RecruitPNG.Web.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobService jobService;
        private readonly ICompanyService companyService;
        private readonly IResumeService resumeService;
        private readonly IJobApplicationService jobApplicationService;
        //addaed
        private readonly ICountryService countryService;
        private readonly ICityService cityService;
        private readonly ICountyService countyService;

        public JobController(IJobService jobService, ICompanyService companyService, IResumeService resumeService,
            IJobApplicationService jobApplicationService, ICityService cityService, ICountyService countyService, ICountryService countryService)
        {
            this.jobService = jobService;
            this.companyService = companyService;
            this.resumeService = resumeService;
            this.jobApplicationService = jobApplicationService;
            this.countryService = countryService;
            this.cityService = cityService;
            this.countyService = countyService;
        }
        public IActionResult Index()
        {
            var jobs = jobService.GetAll();
            return View(jobs);
        }

        [Authorize(Roles = "Company")]
        //Create
        public IActionResult Create()
        {

            var job = new Job();
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name");
            //add
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            job.PublishDate = DateTime.Now;
            job.EndDate = job.PublishDate.AddDays(30);
            return View(job);

        }
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Job job)
        {
            if (ModelState.IsValid)
            {
                jobService.Insert(job);
                return RedirectToAction(nameof(Edit), new { id = job.Id, saved = true });
            }
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            return View(job);

        }
        [Authorize(Roles = "Company")]
        //Edit
        public IActionResult Edit(string id, bool saved)
        {
            var job = jobService.Get(id);
            ViewBag.Saved = saved;
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            ViewData["CountryId"] = new SelectList(countryService.GetAll(), "Id", "Name");
            ViewData["CountyId"] = new SelectList(countyService.GetAll(), "Id", "Name");
            ViewData["CityId"] = new SelectList(cityService.GetAll(), "Id", "Name");
            return View(job);
        }
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, Job job)
        {
            if (ModelState.IsValid)
            {
                jobService.Update(job);
                return RedirectToAction(nameof(Edit), new { id = job.Id, saved = true });
            }
            ViewBag.CompanyId = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", job.CompanyId);
            return View(job);

        }
        [Authorize(Roles = "Company")]
        //Delete
        public IActionResult Delete(string id)
        {
            jobService.Delete(id);
            return RedirectToAction("MyJobs");
        }
        [Authorize(Roles = "Company")]
        //MyJobs
        public IActionResult MyJobs()
        {
            var myJobs = jobService.GetAllByUserName(User.Identity.Name).ToList();
            return View(myJobs);
        }

        //Details
        public IActionResult Details(string id)
        {
            var job = jobService.Get(id);
            return View(job);

        }
        [Authorize(Roles = "Candidate")]
        public IActionResult Apply(string jobId)
        {
            var jobEmployer = "";

            var job = jobService.Get(jobId);
            jobEmployer = job.Company.Name; // kime / firma adı

            //var message = new Message() { To = job.CompanyId, ToName = jobEmployer, Title = job.Title };

            var ja = new JobApplication() { JobId = jobId};
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName");
            ViewData["JobId"] = new SelectList(jobApplicationService.GetAll(), "Id", "Name");
            return View(ja);
        }
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        public IActionResult Apply(JobApplication ja)
        {
            if (ModelState.IsValid)
            {
                jobApplicationService.Insert(ja);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", ja.ResumeId);
            return View(ja);

        }

        public IActionResult Success()
        {
            return View();
        }

    }
}

RecruitPNG.Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RecruitPNG.Models;
using RecruitPNG.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecruitPNG.Web.Controllers
{
    public class MessagesController : ControllerBase
    {
        private readonly IMessageService messageService;
        private readonly ICompanyService companyService;
        private readonly IResumeService resumeService;
        private readonly IJobService jobService;
        public MessagesController(IMessageService messageService, ICompanyService companyService, IResumeService resumeService, IJobService jobService)
        {
            this.messageService = messageService;
            this.companyService = companyService;
            this.resumeService = resumeService;
            this.jobService = jobService;
        }
        [Authorize(Roles = "Company")]
        public IActionResult MyMessagesSentToMyCompanies()
        {
            var mycompanies = companyService.GetAllByUserName(User.Identity.Name).Select(c=>c.Id).ToList();
            var mymessages = messageService.GetAllByTo(mycompanies);
            return View(mymessages);
        }
        [Authorize(Roles = "Candidate")]
        public IActionResult MyMessagesSentToMyResumes()
        {
            var myresumes = resumeService.GetAllByUserName(User.Identity.Name).Select(c => c.Id).ToList(); // resumes
            var mymessages = messageService.GetAllByTo(myresumes);
            return View(mymessages);
        }
        [Authorize(Roles = "Company")]
        public IActionResult SendMessageToResume(string resumeId)
        {
            var toName = "";
            
            var resume = resumeService.Get(resumeId);
            toName = resume.ResumeName; // resuem name
           
            var message = new Message(){ To = resumeId, ToName = toName };
            ViewBag.MyCompanies = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name"); // resume
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Company")]
        public IActionResult SendMessageToResume(Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = companyService.Get(message.From).Name; // kimden
                message.ToName = resumeService.Get(message.To).ResumeName; // kime
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyCompanies = new SelectList(companyService.GetAllByUserName(User.Identity.Name), "Id", "Name", message.From);
            return View(message);
        }

        public IActionResult Success()
        {
            return View();
        }

        public IActionResult Details(string id)
        {
            var message = messageService.Get(id);

            return View(message);

        }
        // Candidate to employer
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToCompany(string companyId) // companyId: message to employer job
        {
            
            var toName = "";

            var company = companyService.Get(companyId);
            toName = company.Name + " " + company.ContactName; // employer contat

            var message = new Message() { To = companyId, ToName = toName };
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName"); // select to 
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToCompany(Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = resumeService.Get(message.From).ResumeName; // kimden / özgeçmiş
                message.ToName = companyService.Get(message.To).Name; // kime / firma
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", message.From);
            return View(message);
        }

        // aday ilan sahibi firmaya mesaj gönderiyor
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToJob(string jobId)
        {
            var toName = "";

            var job = jobService.Get(jobId);
            toName = job.Company.Name; // kime / firma adı

            var message = new Message() { To = job.CompanyId, ToName = toName, Title = job.Title };
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName"); // kimden
            return View(message);
        }

        [HttpPost]
        [Authorize(Roles = "Candidate")]
        public IActionResult SendMessageToJob(string jobId, Message message)
        {
            if (ModelState.IsValid)
            {
                message.FromName = resumeService.Get(message.From).ResumeName; // kimden
                message.ToName = companyService.Get(message.To).Name; // kime
                messageService.Insert(message);
                return RedirectToAction("Success");
            }
            ViewBag.MyResumes = new SelectList(resumeService.GetAllByUserName(User.Identity.Name), "Id", "ResumeName", message.From);
            return View(message);
        }
    }
}

RecruitPNG.Web/Views/Companies/Details.cshtml
@model RecruitPNG.Models.Company

@{
    ViewData["Title"] = "Details";
}
<link href="/assets/pages/css/blog.min.css" rel="stylesheet" type="text/css" />
<div class="page-content-inner">
    <div class="blog-page blog-content-2">
        <div class="row">
            <div class="col-lg-9">
                <div class="blog-single-content bordered blog-container">
                    <div class="blog-single-head">
                        <h1 class="blog-single-head-title">@Model.Name</h1>
                        @if (!string.IsNullOrEmpty(Model.Logo))
                        {
                            <img src="~/Uploads/Companies/@Model.Logo" width="150" class="pull-right" />
                        }
                    </div>

                    <div class="blog-single-desc">

                        @Html.Raw(Model.Description)
                        <br />
                        <fieldset>
                            
                            <legend>Contact</legend>
                            <ul>
                                <li>
                                    <strong>Conatct person:</strong>
                                    @Model.ContactName
                                </li>
                                <li>
                                    <strong>Web Site:</strong>
                                    <a href="@Model.Website">@Model.Website</a>
                                </li>
                                <li>
                                    <strong>Adres:</strong>
                                    @Model.Address
                                    @Model.County?.Name/@Model.City?.Name
                                    @Model.Country?.Name
                                </li>
                                
                            </ul>
                        </fieldset>
                        <br />
                        <fieldset>
                            <legend>Vacancies</legend>
                            <table id="myTable" class="table">
                                <thead>
                                    <tr>
                                        <th>
                                           Advertised Positions
                                        </th>

                                       
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Jobs)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Title)
                                            </td>

                                            <td>
                                                <a asp-action="Details" asp-route-id=@item.Id asp-controller="Job" asp-area="" class="btn btn-info btn-sm">Details</a>
                                                @if (User.IsInRole("Candidate"))
                                                {
                                                    <a asp-action="Apply" asp-route-id="@item.Id" asp-controller="Job" asp-area="" class="btn btn-primary btn-sm">Apply</a>
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            
                        </fieldset>
                    </div>

                    
                </div>

            </div>
            <div class="col-lg-3">
                <div class="blog-single-sidebar bordered blog-container">
                    <div>
                        <h4>Other Details</h4>
                    </div>
                    <hr />
                    <div class="blog-single-sidebar-recent">
                        <p>
                            <strong>Sector:</strong><br />@Model.Sector?.Name
                        </p>
                        
                        
                        <p>
                            <strong>Date published:</strong><br />@string.Format("{0:dd.MM.yyyy}", Model.CreateDate)
                        </p>
                        

                    </div>



                </div>
            </div>
        </div>
    </div>

    </div>

RecruitPNG.Web/Views/Companies/Index.cshtml
@model IEnumerable<RecruitPNG.Models.Company>

@{
    ViewData["Title"] = "Companies";
}
<link href="~/assets/cdn/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/cdn/responsive.dataTables.min.css" rel="stylesheet" />

<table id="tblRecords" class="table">
    <thead>
        <tr>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.County)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Sector)
            </th>
            <th class="text-nowrap all" data-orderable="false"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-nowrap">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.City.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.County.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Sector.Name)
                </td>

            <td class="text-nowrap">
                <a asp-action="Details" asp-controller="Companies" asp-route-Id="@item.Id" class="btn btn-default btn-sm">Details</a>
                @if (User.IsInRole("Candidate")) { 
                <a asp-action="SendMessageToCompany" asp-controller="Messages" asp-route-companyId="@item.Id" class="btn btn-warning btn-sm"><i class="fa fa-envelope-o"></i>Send message</a>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/assets/cdn/jquery.dataTables.min.js"></script>
    <script src="~/assets/cdn/dataTables.responsive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblRecords').DataTable({
                responsive: true,
                
            });
        });
    </script>
}

RecruitPNG.Web/Views/Companies/MyCompanies.cshtml
@model IEnumerable<RecruitPNG.Models.Company>

@{
    ViewData["Title"] = "My company";
}

<link href="~/assets/cdn/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/assets/cdn/responsive.dataTables.min.css" rel="stylesheet" />
<p>
    <a asp-action="Create" class="btn btn-primary">Create new</a>
</p>

<table id="tblRecords" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>@Html.DisplayNameFor(model => model.Logo)</th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.County)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sector)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>@Html.DisplayNameFor(model => model.Phone)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
            <th>@Html.DisplayNameFor(model => model.ContactName)</th>
            <th>
                @Html.DisplayNameFor(model => model.IsApproved)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>

            <th class="text-nowrap all"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td><img src="~/Uploads/@item.Logo" width="50" /></td>
            <td>
                @Html.DisplayFor(modelItem => item.City.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.County.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sector.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>@Html.DisplayFor(modelItem => item.Phone)</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.ContactName)</td>
            <td>
                @Html.DisplayFor(modelItem => item.IsApproved)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>

            <td class="text-nowrap">
                <a asp-action="Details" asp-controller="Companies" asp-area="" asp-route-Id="@item.Id" class="btn btn-info btn-sm">Details</a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</a>
                <a asp-action="MyJobApplicants" asp-controller="JobApplications" asp-area="" asp-route-Id="@item.Id" class="btn btn-default btn-sm">Applicants</a>

            </td>
        </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script src="~/assets/cdn/jquery.dataTables.min.js"></script>
    <script src="~/assets/cdn/dataTables.responsive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblRecords').DataTable({
                responsive: true,
               
            });
        });
    </script>
}